apiVersion: batch/v1
kind: Job
metadata:
  name: app-wxwork
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: wxwork-notification
        image: curlimages/curl
        command:
          - "curl"
          - "--request"
          - "POST"
          - "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=gNBSBnZYka8dQn1I8PlxIuNj_V0BPNX2sYQodnTGgWE"
          - "--header"
          - "'Content-Type: application/json'"
          - "--data-raw"
          - "{\"msgtype\": \"text\",\"text\": {\"content\": \"hello world\"}}"
      restartPolicy: Never
  backoffLimit: 1
