apiVersion: v1
kind: Service
metadata:
  name: flask-single-demo
  namespace: flask-single-demo
  labels:
    app: flask-single-demo
    version: v1
spec:
  ports:
    - name: http-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: flask-single-demo
    version: v1
  type: NodePort
